import type { Metadata } from "next";
import "../scss/globals.scss";
import {SessionProvider} from "next-auth/react";
import Favicons from "@/components/layout/includes/favicons";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400,500,700&family=Open+Sans:wght@400&display=swap" rel="stylesheet"/>
        <Favicons/>
      </head>
      <body>
      {children}
      </body>
    </html>
  );
}
